// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// PrivateMST
Rcpp::NumericMatrix PrivateMST(int order, Rcpp::DataFrame Elist, double privacydegree);
RcppExport SEXP _privateMST_PrivateMST(SEXP orderSEXP, SEXP ElistSEXP, SEXP privacydegreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type Elist(ElistSEXP);
    Rcpp::traits::input_parameter< double >::type privacydegree(privacydegreeSEXP);
    rcpp_result_gen = Rcpp::wrap(PrivateMST(order, Elist, privacydegree));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_privateMST_PrivateMST", (DL_FUNC) &_privateMST_PrivateMST, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_privateMST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
