# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute approximate MST from an arbitrary graph using PAMST method
#' @param order Number of nodes in the graph
#' @param Elist edges list as a data.frame
#' @param privacydegree degree of privacy
#' @return The approximate MST using the PAMST algorithm
#' @export
#' @examples
#' n <- 70
#' prob <- 0.1
#' ## Generate random Erdos-Renyi graph
#' graph <- erdos.renyi.game(n, prob, type="gnp",directed = FALSE, loops = FALSE)
#' ## Assign random weights to the edges, using an uniform probability distribution
#' E(graph)$weight <- runif(ecount(graph),0,10)
#' eps <- 0.6
#' Dataframe=igraph::as_data_frame(graph,what="edges")
#' PMST <- PAMST(n,Dataframe,eps)
#' print(sum( PMST[,3] ))
#' print(sum(E(mst(graph))$weight))
#'
#' ## plot the resulting MST
#' ## Be careful the ids are not allowed to be 0 !
#' approxMST <- igraph::graph_from_edgelist(cbind(PMST[,1]+1,PMST[,2]+1),directed = FALSE)
#' mylayout <- layout.auto(graph)
#' par(mfrow=c(1,2))
#' plot(graph, layout=mylayout, vertex.size=5, vertex.label=NA)
#' plot(approxMST, layout=mylayout, vertex.size=5, vertex.label=NA)
#'
PAMST <- function(order, Elist, privacydegree) {
    .Call(`_privateMST_PAMST`, order, Elist, privacydegree)
}

