# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute approximate MST from an arbitrary graph
#' @param order Number of nodes in the graph
#' @param Elist edges list as a data.frame
#' @param privacydegree degree of privacy
#' @return The approximate MST using the PAMST algorithm
#' @export
PrivateMST <- function(order, Elist, privacydegree) {
    .Call(`_privateMST_PrivateMST`, order, Elist, privacydegree)
}

